Auto refresh gnome after IDE install
BenoitRoux0/fttb pull request #8
Opened 2024-09-28 14:46 UTC by gd-harco

2024-09-29 14:20 UTC, BenoitRoux0 requested changes

2024-09-29 14:20 UTC, BenoitRoux0 commented on src/fttb/utils.py
> +def get_arc
Cannot work

2024-09-29 14:22 UTC, gd-harco commented on src/fttb/utils.py
> +def get_arc
My bad,leftover from other branch

2024-10-23 15:03 UTC, BenoitRoux0 approved these changes

2024-10-23 15:04 UTC, merged